// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function height(x) {
  if (x) {
    return x._3;
  } else {
    return 0;
  }
}

function printTreeRec(_t) {
  while(true) {
    var t = _t;
    if (!t) {
      return ;
    }
    printTreeRec(t._0);
    console.log(t._1);
    _t = t._2;
    continue ;
  };
}

exports.height = height;
exports.printTreeRec = printTreeRec;
/* No side effect */
