// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Base = require("./Base.js");

function create(left, val, right) {
  var hl = Base.height(left);
  var hr = Base.height(right);
  return /* Node */{
          _0: left,
          _1: val,
          _2: right,
          _3: hl > hr ? hl + 1 | 0 : hr + 1 | 0
        };
}

function add(val, tree) {
  if (!tree) {
    return /* Node */{
            _0: /* Empty */0,
            _1: val,
            _2: /* Empty */0,
            _3: 1
          };
  }
  var right = tree._2;
  var v = tree._1;
  var left = tree._0;
  if (val < v) {
    return create(add(val, left), v, right);
  } else if (val > v) {
    return create(left, v, add(val, right));
  } else {
    return tree;
  }
}

var root = /* Node */{
  _0: /* Empty */0,
  _1: 1,
  _2: /* Empty */0,
  _3: 0
};

var newRoot = add(1, root);

exports.create = create;
exports.add = add;
exports.root = root;
exports.newRoot = newRoot;
/* newRoot Not a pure module */
